// This file is generated by the Omarchy theme hook (45-quickshell.sh).
// Placeholder values — overwritten on install and on every theme change.

import QtQuick

QtObject {
    id: m3

    property color m3primary: "#888888"
    property color m3onPrimary: "#f5f5f5"

    property color m3primaryContainer: "#444444"
    property color m3onPrimaryContainer: "#f5f5f5"

    property color m3secondary: "#666666"
    property color m3onSecondary: "#f5f5f5"

    property color m3secondaryContainer: "#3a3a3a"
    property color m3onSecondaryContainer: "#f5f5f5"

    property color m3background: "#1e1e1e"
    property color m3onBackground: "#cccccc"

    property color m3surface: "#222222"

    property color m3surfaceContainerLow: "#252525"
    property color m3surfaceContainer: "#2a2a2a"
    property color m3surfaceContainerHigh: "#303030"
    property color m3surfaceContainerHighest: "#383838"

    property color m3onSurface: "#cccccc"

    property color m3surfaceVariant: "#2e2e2e"
    property color m3onSurfaceVariant: "#999999"

    property color m3inverseSurface: "#cccccc"
    property color m3inverseOnSurface: "#1e1e1e"

    property color m3outline: "#555555"
    property color m3outlineVariant: "#333333"

    property color m3shadow: "#000000"
}
